### ISSUE TITLE
Role of Phase for square oscillator

### ISSUE THREAD

**Issue by DanHickstein** [marceluda/rp_lock-in_pid#8]
Thank you for providing this useful piece of software! We are trying to use it to set up a PDH lock to an optical cavity.

I'm stuck trying to get the lock-in signal to have the correct "dispersive lineshape" that you show in your example video. In the image below, the input is Channel 1 and sqYo is channel 2. I would think that changing the phase would change that I see on sqYo, but it does not. Am I thinking about this correctly?

![image](https://user-images.githubusercontent.com/1107796/138983214-55e82cd0-3bbd-4228-a338-3be295c52503.png)

**Comment by marceluda** [comment]
El mar, 26 oct 2021 a las 22:15, Danhickstein ***@***.***>)
escribió:

> Thank you for providing this useful piece of software! We are trying to
> use it to set up a PDH lock to an optical cavity.
>

You are welcome



> I'm stuck trying to get the lock-in signal to have the correct "dispersive
> lineshape" that you show in your example video. In the image below, the
> input is Channel 1 and sqYo is channel 2. I would think that changing the
> phase would change that I see on sqYo, but it does not. Am I thinking about
> this correctly?
>

If you want to use the phase shift you have to choose the sqF signal (
https://marceluda.github.io/rp_lock-in_pid/TheApp/instruments/instruments_04_lock-in/
). If you only want a 90 degree shift you can switch from sqY to sqX .

**Comment by DanHickstein** [comment]
Thanks for the information! This helps a lot.

When using the full 30 MHz modulation, the phase shift options are very limited. I guess this limitation comes from the Red Pitaya itself.

But, when I use the Red Pitaya in "Oscilloscope and Function Generator" mode, I can make two sine waves at 50 MHz and can control the phase between them. I checked on a real oscilloscope, and the two outputs look pretty good. So, it's interesting the we can't get better control over the phase for the lock-in function.

**Comment by marceluda** [comment]
Yes... that's right. The 30 MHz phase shift  is limited by the  Red Pitaya
itself. The internal FPGA clock is 125 MHz ( 8 ns period), so I can move
with integer multiples of that period.

I don't know what the "Oscilloscope and Function Generator" does. It's
closed software and I cannot access the code. My code is based on
https://github.com/RedPitaya/RedPitaya/tree/master/apps-free/scope+gen ,
which  hasn't got any phase control. The only way I can imagine to surpass
the 8ns limit is to change the DAC comunicacion interfase... but I didn't
worked on that.

**Comment by DanHickstein** [comment]
Hi Marcelo, thanks for your reply! 

I am referring to this App that came with my Red Pitaya. Actually called "Oscilloscope and Signal Generator".
![image](https://user-images.githubusercontent.com/1107796/140541200-152f8a97-2857-4783-88ea-e656490cefd3.png)

Is this the same as the "[scope+gen](https://github.com/RedPitaya/RedPitaya/tree/master/apps-free/scope%2Bgen)" app that you linked to?

**Comment by marceluda** [comment]
No, it is not.

the one you say is closed... and you cannot access the source code

**Comment by DanHickstein** [comment]
Thanks for answering my questions!
